export const TRANSLATIONS = {
  ru: { import: "Импорт", new: "Новый", export: "Экспорт", spriteSheet: "Спрайтшит", projectFile: "Файл проекта", selection: "Выделение", layers: "Слои", recentProjects: "Недавние проекты", createProject: "Создать проект", layer: "Слой", saved: "Проект сохранён", imported: "Файл импортирован", projectImported: "Проект открыт", projectExported: "Файл проекта сохранён", invalidProject: "Не удалось открыть проект", project: "Проект", tools: "Инструменты", pencil: "Карандаш", eraser: "Ластик", fill: "Заливка", picker: "Пипетка", line: "Линия", rectangle: "Прямоугольник", ellipse: "Эллипс", color: "Цвет", brushSize: "Размер кисти", quickActions: "Быстрые действия", undo: "Отменить", clearFrame: "Очистить кадр", canvas: "Холст", grid: "Сетка", animation: "Анимация", preview: "Предпросмотр", speed: "Скорость", frames: "Кадры", duplicate: "Дублировать", copyFrame: "Копировать", pasteFrame: "Вставить", delete: "Удалить", newFrame: "Новый кадр", frameCopied: "Кадр скопирован", framePasted: "Кадр вставлен", emptyFrameClipboard: "Сначала скопируйте кадр" },
  en: { import: "Import", new: "New", export: "Export", spriteSheet: "Sprite sheet", projectFile: "Project file", selection: "Selection", layers: "Layers", recentProjects: "Recent projects", createProject: "Create project", layer: "Layer", saved: "Project saved", imported: "File imported", projectImported: "Project opened", projectExported: "Project file saved", invalidProject: "Could not open project", project: "Project", tools: "Tools", pencil: "Pencil", eraser: "Eraser", fill: "Fill", picker: "Color picker", line: "Line", rectangle: "Rectangle", ellipse: "Ellipse", color: "Color", brushSize: "Brush size", quickActions: "Quick actions", undo: "Undo", clearFrame: "Clear frame", canvas: "Canvas", grid: "Grid", animation: "Animation", preview: "Preview", speed: "Speed", frames: "Frames", duplicate: "Duplicate", copyFrame: "Copy", pasteFrame: "Paste", delete: "Delete", newFrame: "New frame", frameCopied: "Frame copied", framePasted: "Frame pasted", emptyFrameClipboard: "Copy a frame first" },
  pl: { import: "Importuj", new: "Nowy", export: "Eksport", spriteSheet: "Arkusz sprite'ów", projectFile: "Plik projektu", selection: "Zaznaczenie", layers: "Warstwy", recentProjects: "Ostatnie projekty", createProject: "Utwórz projekt", layer: "Warstwa", saved: "Projekt zapisany", imported: "Plik zaimportowany", projectImported: "Projekt otwarty", projectExported: "Plik projektu zapisany", invalidProject: "Nie udało się otworzyć projektu", project: "Projekt", tools: "Narzędzia", pencil: "Ołówek", eraser: "Gumka", fill: "Wypełnienie", picker: "Pipeta", line: "Linia", rectangle: "Prostokąt", ellipse: "Elipsa", color: "Kolor", brushSize: "Rozmiar pędzla", quickActions: "Szybkie akcje", undo: "Cofnij", clearFrame: "Wyczyść klatkę", canvas: "Płótno", grid: "Siatka", animation: "Animacja", preview: "Podgląd", speed: "Prędkość", frames: "Klatki", duplicate: "Duplikuj", copyFrame: "Kopiuj", pasteFrame: "Wklej", delete: "Usuń", newFrame: "Nowa klatka", frameCopied: "Klatka skopiowana", framePasted: "Klatka wklejona", emptyFrameClipboard: "Najpierw skopiuj klatkę" }
};
TRANSLATIONS.es = { ...TRANSLATIONS.en, import: "Importar", new: "Nuevo", export: "Exportar", spriteSheet: "Hoja de sprites", projectFile: "Archivo del proyecto", selection: "Selección", layers: "Capas", recentProjects: "Proyectos recientes", createProject: "Crear proyecto", layer: "Capa", saved: "Proyecto guardado", imported: "Archivo importado", projectImported: "Proyecto abierto", projectExported: "Archivo del proyecto guardado", invalidProject: "No se pudo abrir el proyecto", project: "Proyecto", tools: "Herramientas", pencil: "Lápiz", eraser: "Borrador", fill: "Relleno", picker: "Cuentagotas", line: "Línea", rectangle: "Rectángulo", ellipse: "Elipse", color: "Color", brushSize: "Tamaño del pincel", quickActions: "Acciones rápidas", undo: "Deshacer", clearFrame: "Limpiar fotograma", canvas: "Lienzo", grid: "Cuadrícula", animation: "Animación", preview: "Vista previa", speed: "Velocidad", frames: "Fotogramas", duplicate: "Duplicar", copyFrame: "Copiar", pasteFrame: "Pegar", delete: "Eliminar", newFrame: "Nuevo fotograma", frameCopied: "Fotograma copiado", framePasted: "Fotograma pegado", emptyFrameClipboard: "Primero copia un fotograma" };
TRANSLATIONS.tr = { ...TRANSLATIONS.en, import: "İçe aktar", new: "Yeni", export: "Dışa aktar", spriteSheet: "Sprite sayfası", projectFile: "Proje dosyası", selection: "Seçim", layers: "Katmanlar", recentProjects: "Son projeler", createProject: "Proje oluştur", layer: "Katman", saved: "Proje kaydedildi", imported: "Dosya içe aktarıldı", projectImported: "Proje açıldı", projectExported: "Proje dosyası kaydedildi", invalidProject: "Proje açılamadı", project: "Proje", tools: "Araçlar", pencil: "Kalem", eraser: "Silgi", fill: "Doldur", picker: "Damlalık", line: "Çizgi", rectangle: "Dikdörtgen", ellipse: "Elips", color: "Renk", brushSize: "Fırça boyutu", quickActions: "Hızlı işlemler", undo: "Geri al", clearFrame: "Kareyi temizle", canvas: "Tuval", grid: "Izgara", animation: "Animasyon", preview: "Önizleme", speed: "Hız", frames: "Kareler", duplicate: "Çoğalt", copyFrame: "Kopyala", pasteFrame: "Yapıştır", delete: "Sil", newFrame: "Yeni kare", frameCopied: "Kare kopyalandı", framePasted: "Kare yapıştırıldı", emptyFrameClipboard: "Önce bir kare kopyalayın" };
TRANSLATIONS.pt = { ...TRANSLATIONS.en, import: "Importar", new: "Novo", export: "Exportar", spriteSheet: "Folha de sprites", projectFile: "Arquivo do projeto", selection: "Seleção", layers: "Camadas", recentProjects: "Projetos recentes", createProject: "Criar projeto", layer: "Camada", saved: "Projeto salvo", imported: "Arquivo importado", projectImported: "Projeto aberto", projectExported: "Arquivo do projeto salvo", invalidProject: "Não foi possível abrir o projeto", project: "Projeto", tools: "Ferramentas", pencil: "Lápis", eraser: "Borracha", fill: "Preencher", picker: "Conta-gotas", line: "Linha", rectangle: "Retângulo", ellipse: "Elipse", color: "Cor", brushSize: "Tamanho do pincel", quickActions: "Ações rápidas", undo: "Desfazer", clearFrame: "Limpar quadro", canvas: "Tela", grid: "Grade", animation: "Animação", preview: "Pré-visualização", speed: "Velocidade", frames: "Quadros", duplicate: "Duplicar", copyFrame: "Copiar", pasteFrame: "Colar", delete: "Excluir", newFrame: "Novo quadro", frameCopied: "Quadro copiado", framePasted: "Quadro colado", emptyFrameClipboard: "Copie um quadro primeiro" };
TRANSLATIONS.id = { ...TRANSLATIONS.en, import: "Impor", new: "Baru", export: "Ekspor", spriteSheet: "Lembar sprite", projectFile: "Berkas proyek", selection: "Seleksi", layers: "Lapisan", recentProjects: "Proyek terbaru", createProject: "Buat proyek", layer: "Lapisan", saved: "Proyek disimpan", imported: "Berkas diimpor", projectImported: "Proyek dibuka", projectExported: "Berkas proyek disimpan", invalidProject: "Proyek tidak dapat dibuka", project: "Proyek", tools: "Alat", pencil: "Pensil", eraser: "Penghapus", fill: "Isi warna", picker: "Pipet warna", line: "Garis", rectangle: "Persegi panjang", ellipse: "Elips", color: "Warna", brushSize: "Ukuran kuas", quickActions: "Aksi cepat", undo: "Urungkan", clearFrame: "Bersihkan frame", canvas: "Kanvas", grid: "Kisi", animation: "Animasi", preview: "Pratinjau", speed: "Kecepatan", frames: "Frame", duplicate: "Duplikat", copyFrame: "Salin", pasteFrame: "Tempel", delete: "Hapus", newFrame: "Frame baru", frameCopied: "Frame disalin", framePasted: "Frame ditempel", emptyFrameClipboard: "Salin frame terlebih dahulu" };
Object.assign(TRANSLATIONS.ru, { untitledProject: "Моя анимация", frameLabel: "кадр", cycleLabel: "цикл", onionHelp: "Предыдущий кадр — красный, следующий — синий.", storyboard: "Раскадровка", newProject: "Новый проект", canvasSize: "Размер холста", sizeHelp: "Выберите заготовку или задайте свой размер от 8 до 128 пикселей.", width: "Ширина", height: "Высота", cancel: "Отмена" });
Object.assign(TRANSLATIONS.en, { untitledProject: "My animation", frameLabel: "frame", cycleLabel: "loop", onionHelp: "Previous frame is red, next frame is blue.", storyboard: "Storyboard", newProject: "New project", canvasSize: "Canvas size", sizeHelp: "Choose a preset or enter a custom size from 8 to 128 pixels.", width: "Width", height: "Height", cancel: "Cancel" });
Object.assign(TRANSLATIONS.pl, { untitledProject: "Moja animacja", frameLabel: "klatka", cycleLabel: "pętla", onionHelp: "Poprzednia klatka jest czerwona, następna niebieska.", storyboard: "Scenorys", newProject: "Nowy projekt", canvasSize: "Rozmiar płótna", sizeHelp: "Wybierz ustawienie lub podaj rozmiar od 8 do 128 pikseli.", width: "Szerokość", height: "Wysokość", cancel: "Anuluj" });
Object.assign(TRANSLATIONS.es, { untitledProject: "Mi animación", frameLabel: "fotograma", cycleLabel: "ciclo", onionHelp: "El fotograma anterior es rojo y el siguiente azul.", storyboard: "Guion gráfico", newProject: "Nuevo proyecto", canvasSize: "Tamaño del lienzo", sizeHelp: "Elige un tamaño o introduce uno de 8 a 128 píxeles.", width: "Ancho", height: "Alto", cancel: "Cancelar" });
Object.assign(TRANSLATIONS.tr, { untitledProject: "Animasyonum", frameLabel: "kare", cycleLabel: "döngü", onionHelp: "Önceki kare kırmızı, sonraki kare mavidir.", storyboard: "Hikâye panosu", newProject: "Yeni proje", canvasSize: "Tuval boyutu", sizeHelp: "Bir hazır boyut seçin veya 8–128 piksel arası girin.", width: "Genişlik", height: "Yükseklik", cancel: "İptal" });
Object.assign(TRANSLATIONS.pt, { untitledProject: "Minha animação", frameLabel: "quadro", cycleLabel: "ciclo", onionHelp: "O quadro anterior é vermelho e o próximo é azul.", storyboard: "Storyboard", newProject: "Novo projeto", canvasSize: "Tamanho da tela", sizeHelp: "Escolha um tamanho ou informe de 8 a 128 pixels.", width: "Largura", height: "Altura", cancel: "Cancelar" });
Object.assign(TRANSLATIONS.id, { untitledProject: "Animasi saya", frameLabel: "frame", cycleLabel: "siklus", onionHelp: "Frame sebelumnya merah, frame berikutnya biru.", storyboard: "Storyboard", newProject: "Proyek baru", canvasSize: "Ukuran kanvas", sizeHelp: "Pilih ukuran atau masukkan 8 hingga 128 piksel.", width: "Lebar", height: "Tinggi", cancel: "Batal" });
Object.assign(TRANSLATIONS.ru, { download: "Скачать", exportAnimation: "Скачать анимацию", animatedGif: "Анимированный GIF", gifDescription: "Все кадры, текущая скорость и прозрачный фон", pngDescription: "Текущий кадр", sheetDescription: "Все кадры одной полосой", projectDescription: "Сжатый проект с проверкой целостности" });
Object.assign(TRANSLATIONS.en, { download: "Download", exportAnimation: "Download animation", animatedGif: "Animated GIF", gifDescription: "All frames, current speed and transparent background", pngDescription: "Current frame", sheetDescription: "All frames in one strip", projectDescription: "Compressed project with integrity check" });
Object.assign(TRANSLATIONS.pl, { download: "Pobierz", exportAnimation: "Pobierz animację", animatedGif: "Animowany GIF", gifDescription: "Wszystkie klatki, bieżąca prędkość i przezroczyste tło", pngDescription: "Bieżąca klatka", sheetDescription: "Wszystkie klatki w jednym pasku", projectDescription: "Skompresowany projekt z kontrolą integralności" });
Object.assign(TRANSLATIONS.es, { download: "Descargar", exportAnimation: "Descargar animación", animatedGif: "GIF animado", gifDescription: "Todos los fotogramas, velocidad actual y fondo transparente", pngDescription: "Fotograma actual", sheetDescription: "Todos los fotogramas en una tira", projectDescription: "Proyecto comprimido con control de integridad" });
Object.assign(TRANSLATIONS.tr, { download: "İndir", exportAnimation: "Animasyonu indir", animatedGif: "Animasyonlu GIF", gifDescription: "Tüm kareler, mevcut hız ve şeffaf arka plan", pngDescription: "Geçerli kare", sheetDescription: "Tüm kareler tek şeritte", projectDescription: "Bütünlük denetimli sıkıştırılmış proje" });
Object.assign(TRANSLATIONS.pt, { download: "Baixar", exportAnimation: "Baixar animação", animatedGif: "GIF animado", gifDescription: "Todos os quadros, velocidade atual e fundo transparente", pngDescription: "Quadro atual", sheetDescription: "Todos os quadros em uma faixa", projectDescription: "Projeto compactado com verificação de integridade" });
Object.assign(TRANSLATIONS.id, { download: "Unduh", exportAnimation: "Unduh animasi", animatedGif: "GIF animasi", gifDescription: "Semua frame, kecepatan saat ini, dan latar transparan", pngDescription: "Frame saat ini", sheetDescription: "Semua frame dalam satu strip", projectDescription: "Proyek terkompresi dengan pemeriksaan integritas" });
Object.assign(TRANSLATIONS.ru, { recoveryTitle: "Восстановить работу?", recoveryCopy: "Редактор завершил работу неожиданно. Найдена сохранённая рабочая копия.", discardRecovery: "Не восстанавливать", restoreRecovery: "Восстановить", backupVersions: "Резервные версии", backupHelp: "До восьми последних отличающихся версий текущего проекта.", restoreVersion: "Восстановить", noBackups: "Резервных версий пока нет", shortcutMap: "Горячие клавиши", shortcutTools: "Инструменты", shortcutEditing: "Редактирование", shortcutView: "Просмотр", pasteAfter: "Вставить после", pasteBefore: "Вставить до", zoomIn: "Приблизить", zoomOut: "Отдалить", fitCanvas: "Вписать холст", savedPalettes: "Палитры", defaultPalette: "Основная палитра" });
Object.assign(TRANSLATIONS.en, { recoveryTitle: "Restore your work?", recoveryCopy: "The editor closed unexpectedly. A saved working copy was found.", discardRecovery: "Discard", restoreRecovery: "Restore", backupVersions: "Backup versions", backupHelp: "Up to eight latest distinct versions of the current project.", restoreVersion: "Restore", noBackups: "No backup versions yet", shortcutMap: "Keyboard shortcuts", shortcutTools: "Tools", shortcutEditing: "Editing", shortcutView: "View", pasteAfter: "Paste after", pasteBefore: "Paste before", zoomIn: "Zoom in", zoomOut: "Zoom out", fitCanvas: "Fit canvas", savedPalettes: "Palettes", defaultPalette: "Default palette" });
Object.assign(TRANSLATIONS.pl, { recoveryTitle: "Przywrócić pracę?", recoveryCopy: "Edytor został nieoczekiwanie zamknięty. Znaleziono kopię roboczą.", discardRecovery: "Odrzuć", restoreRecovery: "Przywróć", backupVersions: "Wersje zapasowe", backupHelp: "Do ośmiu ostatnich różnych wersji projektu.", restoreVersion: "Przywróć", noBackups: "Brak wersji zapasowych", shortcutMap: "Skróty klawiszowe", shortcutTools: "Narzędzia", shortcutEditing: "Edycja", shortcutView: "Widok", pasteAfter: "Wklej po", pasteBefore: "Wklej przed", zoomIn: "Powiększ", zoomOut: "Pomniejsz", fitCanvas: "Dopasuj płótno", savedPalettes: "Palety", defaultPalette: "Paleta podstawowa" });
Object.assign(TRANSLATIONS.es, { recoveryTitle: "¿Restaurar el trabajo?", recoveryCopy: "El editor se cerró inesperadamente. Se encontró una copia de trabajo.", discardRecovery: "Descartar", restoreRecovery: "Restaurar", backupVersions: "Versiones de respaldo", backupHelp: "Hasta ocho versiones distintas recientes del proyecto.", restoreVersion: "Restaurar", noBackups: "Aún no hay copias", shortcutMap: "Atajos de teclado", shortcutTools: "Herramientas", shortcutEditing: "Edición", shortcutView: "Vista", pasteAfter: "Pegar después", pasteBefore: "Pegar antes", zoomIn: "Acercar", zoomOut: "Alejar", fitCanvas: "Ajustar lienzo", savedPalettes: "Paletas", defaultPalette: "Paleta principal" });
Object.assign(TRANSLATIONS.tr, { recoveryTitle: "Çalışma geri yüklensin mi?", recoveryCopy: "Düzenleyici beklenmedik şekilde kapandı. Kaydedilmiş bir çalışma kopyası bulundu.", discardRecovery: "At", restoreRecovery: "Geri yükle", backupVersions: "Yedek sürümler", backupHelp: "Projenin en fazla sekiz farklı son sürümü.", restoreVersion: "Geri yükle", noBackups: "Henüz yedek yok", shortcutMap: "Klavye kısayolları", shortcutTools: "Araçlar", shortcutEditing: "Düzenleme", shortcutView: "Görünüm", pasteAfter: "Sonrasına yapıştır", pasteBefore: "Öncesine yapıştır", zoomIn: "Yakınlaştır", zoomOut: "Uzaklaştır", fitCanvas: "Tuvali sığdır", savedPalettes: "Paletler", defaultPalette: "Ana palet" });
Object.assign(TRANSLATIONS.pt, { recoveryTitle: "Restaurar o trabalho?", recoveryCopy: "O editor foi encerrado inesperadamente. Uma cópia de trabalho foi encontrada.", discardRecovery: "Descartar", restoreRecovery: "Restaurar", backupVersions: "Versões de backup", backupHelp: "Até oito versões recentes e diferentes do projeto.", restoreVersion: "Restaurar", noBackups: "Ainda não há backups", shortcutMap: "Atalhos de teclado", shortcutTools: "Ferramentas", shortcutEditing: "Edição", shortcutView: "Visualização", pasteAfter: "Colar depois", pasteBefore: "Colar antes", zoomIn: "Aproximar", zoomOut: "Afastar", fitCanvas: "Ajustar tela", savedPalettes: "Paletas", defaultPalette: "Paleta principal" });
Object.assign(TRANSLATIONS.id, { recoveryTitle: "Pulihkan pekerjaan?", recoveryCopy: "Editor tertutup secara tidak terduga. Salinan kerja tersimpan ditemukan.", discardRecovery: "Buang", restoreRecovery: "Pulihkan", backupVersions: "Versi cadangan", backupHelp: "Hingga delapan versi proyek terbaru yang berbeda.", restoreVersion: "Pulihkan", noBackups: "Belum ada cadangan", shortcutMap: "Pintasan keyboard", shortcutTools: "Alat", shortcutEditing: "Penyuntingan", shortcutView: "Tampilan", pasteAfter: "Tempel setelah", pasteBefore: "Tempel sebelum", zoomIn: "Perbesar", zoomOut: "Perkecil", fitCanvas: "Sesuaikan kanvas", savedPalettes: "Palet", defaultPalette: "Palet utama" });
Object.assign(TRANSLATIONS.ru, { selectAllProjects: "Выбрать все", selectedProjects: "выбрано", deleteSelectedProjects: "Удалить выбранные", deleteAllProjects: "Удалить все", confirmDeleteSelected: "Удалить выбранные проекты?", confirmDeleteAll: "Удалить все проекты? Это действие нельзя отменить.", projectsDeleted: "Проекты удалены" });
Object.assign(TRANSLATIONS.en, { selectAllProjects: "Select all", selectedProjects: "selected", deleteSelectedProjects: "Delete selected", deleteAllProjects: "Delete all", confirmDeleteSelected: "Delete selected projects?", confirmDeleteAll: "Delete all projects? This cannot be undone.", projectsDeleted: "Projects deleted" });
Object.assign(TRANSLATIONS.pl, { selectAllProjects: "Wybierz wszystkie", selectedProjects: "wybrano", deleteSelectedProjects: "Usuń wybrane", deleteAllProjects: "Usuń wszystkie", confirmDeleteSelected: "Usunąć wybrane projekty?", confirmDeleteAll: "Usunąć wszystkie projekty? Tej operacji nie można cofnąć.", projectsDeleted: "Projekty usunięte" });
Object.assign(TRANSLATIONS.es, { selectAllProjects: "Seleccionar todos", selectedProjects: "seleccionados", deleteSelectedProjects: "Eliminar seleccionados", deleteAllProjects: "Eliminar todos", confirmDeleteSelected: "¿Eliminar los proyectos seleccionados?", confirmDeleteAll: "¿Eliminar todos los proyectos? Esta acción no se puede deshacer.", projectsDeleted: "Proyectos eliminados" });
Object.assign(TRANSLATIONS.tr, { selectAllProjects: "Tümünü seç", selectedProjects: "seçildi", deleteSelectedProjects: "Seçilenleri sil", deleteAllProjects: "Tümünü sil", confirmDeleteSelected: "Seçilen projeler silinsin mi?", confirmDeleteAll: "Tüm projeler silinsin mi? Bu işlem geri alınamaz.", projectsDeleted: "Projeler silindi" });
Object.assign(TRANSLATIONS.pt, { selectAllProjects: "Selecionar todos", selectedProjects: "selecionados", deleteSelectedProjects: "Excluir selecionados", deleteAllProjects: "Excluir todos", confirmDeleteSelected: "Excluir os projetos selecionados?", confirmDeleteAll: "Excluir todos os projetos? Esta ação não pode ser desfeita.", projectsDeleted: "Projetos excluídos" });
Object.assign(TRANSLATIONS.id, { selectAllProjects: "Pilih semua", selectedProjects: "dipilih", deleteSelectedProjects: "Hapus yang dipilih", deleteAllProjects: "Hapus semua", confirmDeleteSelected: "Hapus proyek yang dipilih?", confirmDeleteAll: "Hapus semua proyek? Tindakan ini tidak dapat dibatalkan.", projectsDeleted: "Proyek dihapus" });
Object.assign(TRANSLATIONS.ru, { downloadGif: "Скачать GIF" });
Object.assign(TRANSLATIONS.en, { downloadGif: "Download GIF" });
Object.assign(TRANSLATIONS.pl, { downloadGif: "Pobierz GIF" });
Object.assign(TRANSLATIONS.es, { downloadGif: "Descargar GIF" });
Object.assign(TRANSLATIONS.tr, { downloadGif: "GIF indir" });
Object.assign(TRANSLATIONS.pt, { downloadGif: "Baixar GIF" });
Object.assign(TRANSLATIONS.id, { downloadGif: "Unduh GIF" });
Object.assign(TRANSLATIONS.ru, { exportScale: "Размер экспорта", customScale: "Свой", scaleHint: "Увеличение без размытия, каждый пиксель остаётся чётким.", pngDescription: "Текущий кадр в выбранном масштабе", sheetDescription: "Все кадры одной полосой в выбранном масштабе" });
Object.assign(TRANSLATIONS.en, { exportScale: "Export size", customScale: "Custom", scaleHint: "Pixel-perfect scaling with no blur.", pngDescription: "Current frame at the selected scale", sheetDescription: "All frames in one strip at the selected scale" });
Object.assign(TRANSLATIONS.pl, { exportScale: "Rozmiar eksportu", customScale: "Własna", scaleHint: "Skalowanie bez rozmycia, piksele pozostają ostre.", pngDescription: "Bieżąca klatka w wybranej skali", sheetDescription: "Wszystkie klatki w jednym pasku w wybranej skali" });
Object.assign(TRANSLATIONS.es, { exportScale: "Tamaño de exportación", customScale: "Personalizado", scaleHint: "Escalado nítido sin desenfoque.", pngDescription: "Fotograma actual con la escala seleccionada", sheetDescription: "Todos los fotogramas con la escala seleccionada" });
Object.assign(TRANSLATIONS.tr, { exportScale: "Dışa aktarma boyutu", customScale: "Özel", scaleHint: "Bulanıklık olmadan piksel netliğinde ölçekleme.", pngDescription: "Seçilen ölçekte geçerli kare", sheetDescription: "Seçilen ölçekte tek şeritte tüm kareler" });
Object.assign(TRANSLATIONS.pt, { exportScale: "Tamanho da exportação", customScale: "Personalizado", scaleHint: "Ampliação sem desfoque, mantendo os pixels nítidos.", pngDescription: "Quadro atual na escala selecionada", sheetDescription: "Todos os quadros na escala selecionada" });
Object.assign(TRANSLATIONS.id, { exportScale: "Ukuran ekspor", customScale: "Kustom", scaleHint: "Penskalaan tajam tanpa buram.", pngDescription: "Frame saat ini pada skala terpilih", sheetDescription: "Semua frame pada skala terpilih" });
Object.assign(TRANSLATIONS.ru, { challenges: "Испытания", challengeHeading: "Испытания", challengeIntro: "Шесть заданий: от первого рисунка до покадровой анимации.", checkChallenge: "Проверить", startChallenge: "Начать", free: "Бесплатно", completed: "Пройдено" });
Object.assign(TRANSLATIONS.en, { challenges: "Challenges", challengeHeading: "Challenges", challengeIntro: "Six missions, from a first drawing to frame-by-frame animation.", checkChallenge: "Check", startChallenge: "Start", free: "Free", completed: "Completed" });
Object.assign(TRANSLATIONS.pl, { challenges: "Wyzwania", challengeHeading: "Wyzwania", challengeIntro: "Sześć zadań: od pierwszego rysunku do animacji klatka po klatce.", checkChallenge: "Sprawdź", startChallenge: "Zacznij", free: "Darmowe", completed: "Ukończono" });
Object.assign(TRANSLATIONS.es, { challenges: "Desafíos", challengeHeading: "Desafíos", challengeIntro: "Seis retos, desde el primer dibujo hasta la animación fotograma a fotograma.", checkChallenge: "Comprobar", startChallenge: "Empezar", free: "Gratis", completed: "Completado" });
Object.assign(TRANSLATIONS.tr, { challenges: "Görevler", challengeHeading: "Görevler", challengeIntro: "İlk çizimden kare kare animasyona uzanan altı görev.", checkChallenge: "Kontrol et", startChallenge: "Başla", free: "Ücretsiz", completed: "Tamamlandı" });
Object.assign(TRANSLATIONS.pt, { challenges: "Desafios", challengeHeading: "Desafios", challengeIntro: "Seis desafios, do primeiro desenho à animação quadro a quadro.", checkChallenge: "Verificar", startChallenge: "Começar", free: "Grátis", completed: "Concluído" });
Object.assign(TRANSLATIONS.id, { challenges: "Tantangan", challengeHeading: "Tantangan", challengeIntro: "Enam tantangan, dari gambar pertama hingga animasi frame demi frame.", checkChallenge: "Periksa", startChallenge: "Mulai", free: "Gratis", completed: "Selesai" });
Object.assign(TRANSLATIONS.ru, { enlargeReference: "нажми на образец, чтобы увеличить", reference: "Образец", referenceScale: "Масштаб образца", referenceGrid: "Показывать сетку", fit: "Вписать" });
Object.assign(TRANSLATIONS.en, { enlargeReference: "click the reference to enlarge", reference: "Reference", referenceScale: "Reference scale", referenceGrid: "Show grid", fit: "Fit" });
Object.assign(TRANSLATIONS.pl, { enlargeReference: "kliknij wzór, aby powiększyć", reference: "Wzór", referenceScale: "Skala wzoru", referenceGrid: "Pokaż siatkę", fit: "Dopasuj" });
Object.assign(TRANSLATIONS.es, { enlargeReference: "pulsa el modelo para ampliarlo", reference: "Modelo", referenceScale: "Escala del modelo", referenceGrid: "Mostrar cuadrícula", fit: "Ajustar" });
Object.assign(TRANSLATIONS.tr, { enlargeReference: "büyütmek için örneğe tıkla", reference: "Örnek", referenceScale: "Örnek ölçeği", referenceGrid: "Izgarayı göster", fit: "Sığdır" });
Object.assign(TRANSLATIONS.pt, { enlargeReference: "clique no modelo para ampliar", reference: "Modelo", referenceScale: "Escala do modelo", referenceGrid: "Mostrar grade", fit: "Ajustar" });
Object.assign(TRANSLATIONS.id, { enlargeReference: "klik contoh untuk memperbesar", reference: "Contoh", referenceScale: "Skala contoh", referenceGrid: "Tampilkan kisi", fit: "Sesuaikan" });
Object.assign(TRANSLATIONS.ru, { artistLevel: "Уровень художника", winStreak: "серия побед", missionComplete: "Испытание пройдено", accuracy: "точность", reward: "награда", backToEditor: "В редактор", nextChallenge: "Следующее испытание" });
Object.assign(TRANSLATIONS.en, { artistLevel: "Artist level", winStreak: "win streak", missionComplete: "Challenge complete", accuracy: "accuracy", reward: "reward", backToEditor: "Back to editor", nextChallenge: "Next challenge" });
Object.assign(TRANSLATIONS.pl, { artistLevel: "Poziom artysty", winStreak: "seria zwycięstw", missionComplete: "Wyzwanie ukończone", accuracy: "dokładność", reward: "nagroda", backToEditor: "Do edytora", nextChallenge: "Następne wyzwanie" });
Object.assign(TRANSLATIONS.es, { artistLevel: "Nivel de artista", winStreak: "racha", missionComplete: "Desafío completado", accuracy: "precisión", reward: "recompensa", backToEditor: "Volver al editor", nextChallenge: "Siguiente desafío" });
Object.assign(TRANSLATIONS.tr, { artistLevel: "Sanatçı seviyesi", winStreak: "zafer serisi", missionComplete: "Görev tamamlandı", accuracy: "doğruluk", reward: "ödül", backToEditor: "Editöre dön", nextChallenge: "Sonraki görev" });
Object.assign(TRANSLATIONS.pt, { artistLevel: "Nível do artista", winStreak: "sequência", missionComplete: "Desafio concluído", accuracy: "precisão", reward: "recompensa", backToEditor: "Voltar ao editor", nextChallenge: "Próximo desafio" });
Object.assign(TRANSLATIONS.id, { artistLevel: "Level seniman", winStreak: "rentetan menang", missionComplete: "Tantangan selesai", accuracy: "akurasi", reward: "hadiah", backToEditor: "Kembali ke editor", nextChallenge: "Tantangan berikutnya" });
Object.assign(TRANSLATIONS.ru, { framePlan: "План по кадрам" });
Object.assign(TRANSLATIONS.en, { framePlan: "Frame plan" });
Object.assign(TRANSLATIONS.pl, { framePlan: "Plan klatek" });
Object.assign(TRANSLATIONS.es, { framePlan: "Plan de fotogramas" });
Object.assign(TRANSLATIONS.tr, { framePlan: "Kare planı" });
Object.assign(TRANSLATIONS.pt, { framePlan: "Plano de quadros" });
Object.assign(TRANSLATIONS.id, { framePlan: "Rencana frame" });
Object.assign(TRANSLATIONS.ru, { footerAutosave: "Автосохранение включено" });
Object.assign(TRANSLATIONS.en, { footerAutosave: "Autosave enabled" });
Object.assign(TRANSLATIONS.pl, { footerAutosave: "Autozapis włączony" });
Object.assign(TRANSLATIONS.es, { footerAutosave: "Autoguardado activado" });
Object.assign(TRANSLATIONS.tr, { footerAutosave: "Otomatik kayıt açık" });
Object.assign(TRANSLATIONS.pt, { footerAutosave: "Salvamento automático ativo" });
Object.assign(TRANSLATIONS.id, { footerAutosave: "Simpan otomatis aktif" });
Object.assign(TRANSLATIONS.ru, { footerZoomHint: "Колесо мыши — масштаб холста" });
Object.assign(TRANSLATIONS.en, { footerZoomHint: "Mouse wheel — canvas zoom" });
Object.assign(TRANSLATIONS.pl, { footerZoomHint: "Kółko myszy — powiększenie płótna" });
Object.assign(TRANSLATIONS.es, { footerZoomHint: "Rueda del ratón — zoom del lienzo" });
Object.assign(TRANSLATIONS.tr, { footerZoomHint: "Fare tekerleği — tuval yakınlaştırma" });
Object.assign(TRANSLATIONS.pt, { footerZoomHint: "Roda do mouse — zoom da tela" });
Object.assign(TRANSLATIONS.id, { footerZoomHint: "Roda mouse — zoom kanvas" });
Object.assign(TRANSLATIONS.ru, { currentColor: "Текущий" });
Object.assign(TRANSLATIONS.en, { currentColor: "Current" });
Object.assign(TRANSLATIONS.pl, { currentColor: "Bieżący" });
Object.assign(TRANSLATIONS.es, { currentColor: "Actual" });
Object.assign(TRANSLATIONS.tr, { currentColor: "Geçerli" });
Object.assign(TRANSLATIONS.pt, { currentColor: "Atual" });
Object.assign(TRANSLATIONS.id, { currentColor: "Saat ini" });
Object.assign(TRANSLATIONS.ru, { play: "Запустить", pause: "Пауза" });
Object.assign(TRANSLATIONS.en, { play: "Play", pause: "Pause" });
Object.assign(TRANSLATIONS.pl, { play: "Odtwórz", pause: "Pauza" });
Object.assign(TRANSLATIONS.es, { play: "Reproducir", pause: "Pausa" });
Object.assign(TRANSLATIONS.tr, { play: "Oynat", pause: "Duraklat" });
Object.assign(TRANSLATIONS.pt, { play: "Reproduzir", pause: "Pausar" });
Object.assign(TRANSLATIONS.id, { play: "Putar", pause: "Jeda" });
Object.assign(TRANSLATIONS.ru, { dailyChallenge: "Задание дня", dailyBonus: "Ежедневный бонус", dailyDone: "Сегодня выполнено", dailyStreak: "дней подряд" });
Object.assign(TRANSLATIONS.en, { dailyChallenge: "Daily challenge", dailyBonus: "Daily bonus", dailyDone: "Completed today", dailyStreak: "days in a row" });
Object.assign(TRANSLATIONS.pl, { dailyChallenge: "Wyzwanie dnia", dailyBonus: "Dzienny bonus", dailyDone: "Ukończono dziś", dailyStreak: "dni z rzędu" });
Object.assign(TRANSLATIONS.es, { dailyChallenge: "Desafío diario", dailyBonus: "Bono diario", dailyDone: "Completado hoy", dailyStreak: "días seguidos" });
Object.assign(TRANSLATIONS.tr, { dailyChallenge: "Günlük görev", dailyBonus: "Günlük bonus", dailyDone: "Bugün tamamlandı", dailyStreak: "günlük seri" });
Object.assign(TRANSLATIONS.pt, { dailyChallenge: "Desafio diário", dailyBonus: "Bônus diário", dailyDone: "Concluído hoje", dailyStreak: "dias seguidos" });
Object.assign(TRANSLATIONS.id, { dailyChallenge: "Tantangan harian", dailyBonus: "Bonus harian", dailyDone: "Selesai hari ini", dailyStreak: "hari berturut-turut" });
Object.assign(TRANSLATIONS.ru, { courseProgress: "Прогресс курса", recommended: "Следующее" });
Object.assign(TRANSLATIONS.en, { courseProgress: "Course progress", recommended: "Up next" });
Object.assign(TRANSLATIONS.pl, { courseProgress: "Postęp kursu", recommended: "Następne" });
Object.assign(TRANSLATIONS.es, { courseProgress: "Progreso del curso", recommended: "Siguiente" });
Object.assign(TRANSLATIONS.tr, { courseProgress: "Kurs ilerlemesi", recommended: "Sıradaki" });
Object.assign(TRANSLATIONS.pt, { courseProgress: "Progresso do curso", recommended: "Próximo" });
Object.assign(TRANSLATIONS.id, { courseProgress: "Progres kursus", recommended: "Berikutnya" });
Object.assign(TRANSLATIONS.ru, { newLayer: "Новый слой", showLayer: "Показать слой", hideLayer: "Скрыть слой", moveLayerUp: "Поднять слой", moveLayerDown: "Опустить слой" });
Object.assign(TRANSLATIONS.en, { newLayer: "New layer", showLayer: "Show layer", hideLayer: "Hide layer", moveLayerUp: "Move layer up", moveLayerDown: "Move layer down" });
Object.assign(TRANSLATIONS.pl, { newLayer: "Nowa warstwa", showLayer: "Pokaż warstwę", hideLayer: "Ukryj warstwę", moveLayerUp: "Przenieś wyżej", moveLayerDown: "Przenieś niżej" });
Object.assign(TRANSLATIONS.es, { newLayer: "Nueva capa", showLayer: "Mostrar capa", hideLayer: "Ocultar capa", moveLayerUp: "Subir capa", moveLayerDown: "Bajar capa" });
Object.assign(TRANSLATIONS.tr, { newLayer: "Yeni katman", showLayer: "Katmanı göster", hideLayer: "Katmanı gizle", moveLayerUp: "Katmanı yukarı taşı", moveLayerDown: "Katmanı aşağı taşı" });
Object.assign(TRANSLATIONS.pt, { newLayer: "Nova camada", showLayer: "Mostrar camada", hideLayer: "Ocultar camada", moveLayerUp: "Mover camada para cima", moveLayerDown: "Mover camada para baixo" });
Object.assign(TRANSLATIONS.id, { newLayer: "Lapisan baru", showLayer: "Tampilkan lapisan", hideLayer: "Sembunyikan lapisan", moveLayerUp: "Naikkan lapisan", moveLayerDown: "Turunkan lapisan" });
Object.assign(TRANSLATIONS.ru, { myProjects: "Мои проекты", searchProjects: "Найти проект", sortRecent: "Сначала новые", sortName: "По названию", noProjects: "Сохранённых проектов пока нет.", noProjectMatches: "Ничего не найдено" });
Object.assign(TRANSLATIONS.en, { myProjects: "My projects", searchProjects: "Search projects", sortRecent: "Newest first", sortName: "By name", noProjects: "No saved projects yet.", noProjectMatches: "No projects found" });
Object.assign(TRANSLATIONS.pl, { myProjects: "Moje projekty", searchProjects: "Szukaj projektów", sortRecent: "Najnowsze", sortName: "Według nazwy", noProjects: "Brak zapisanych projektów.", noProjectMatches: "Nie znaleziono projektów" });
Object.assign(TRANSLATIONS.es, { myProjects: "Mis proyectos", searchProjects: "Buscar proyectos", sortRecent: "Más recientes", sortName: "Por nombre", noProjects: "Aún no hay proyectos guardados.", noProjectMatches: "No se encontraron proyectos" });
Object.assign(TRANSLATIONS.tr, { myProjects: "Projelerim", searchProjects: "Proje ara", sortRecent: "En yeniler", sortName: "Ada göre", noProjects: "Henüz kayıtlı proje yok.", noProjectMatches: "Proje bulunamadı" });
Object.assign(TRANSLATIONS.pt, { myProjects: "Meus projetos", searchProjects: "Buscar projetos", sortRecent: "Mais recentes", sortName: "Por nome", noProjects: "Ainda não há projetos salvos.", noProjectMatches: "Nenhum projeto encontrado" });
Object.assign(TRANSLATIONS.id, { myProjects: "Proyek saya", searchProjects: "Cari proyek", sortRecent: "Terbaru", sortName: "Menurut nama", noProjects: "Belum ada proyek tersimpan.", noProjectMatches: "Proyek tidak ditemukan" });
const $ = (selector) => document.querySelector(selector);
export const CHALLENGE_UI = {
  ru: { level: "Уровень", challenge: "Испытание", currentFrame: "Сейчас рисуем кадр", frame: "Кадр", retry: "Улучшить результат", started: "Испытание началось — образец всегда рядом", similarity: "сходство с образцом", colors: "количество цветов", frames: "количество кадров", motion: "движение между кадрами", sequence: "порядок и вид кадров", completed: "Испытание пройдено", notReady: "Пока не готово", improve: "Нужно улучшить", saved: "Отличная работа. Результат сохранён в твоём прогрессе.", xpEarned: "XP уже получен", newResult: "Новый результат сохранён. Продолжай серию!", bestUpdated: "Лучший результат обновлён, награда за это задание уже была получена.", closed: "Режим испытания закрыт, рисунок сохранён", ranks: ["Новичок", "Пиксель-художник", "Аниматор", "Мастер пикселей"] },
  en: { level: "Level", challenge: "Challenge", currentFrame: "Current target frame", frame: "Frame", retry: "Improve result", started: "Challenge started — keep an eye on the reference", similarity: "template similarity", colors: "color count", frames: "frame count", motion: "movement between frames", sequence: "frame order and appearance", completed: "Challenge completed", notReady: "Not quite yet", improve: "Improve", saved: "Great work. Your progress has been saved.", xpEarned: "XP already earned", newResult: "New result saved. Keep the streak going!", bestUpdated: "Best score updated; this mission's XP was already collected.", closed: "Challenge mode closed, your drawing is safe", ranks: ["Rookie", "Pixel Artist", "Animator", "Pixel Master"] },
  pl: { level: "Poziom", challenge: "Wyzwanie", currentFrame: "Teraz rysujesz klatkę", frame: "Klatka", retry: "Popraw wynik", started: "Wyzwanie rozpoczęte — wzór jest zawsze obok", similarity: "podobieństwo do wzoru", colors: "liczba kolorów", frames: "liczba klatek", motion: "ruch między klatkami", sequence: "kolejność i wygląd klatek", completed: "Wyzwanie ukończone", notReady: "Jeszcze nie gotowe", improve: "Popraw", saved: "Świetna robota. Postęp został zapisany.", xpEarned: "XP już zdobyte", newResult: "Nowy wynik zapisany. Kontynuuj serię!", bestUpdated: "Najlepszy wynik poprawiony; XP za to zadanie już zdobyto.", closed: "Tryb wyzwania zamknięty, rysunek zapisany", ranks: ["Nowicjusz", "Pixel artysta", "Animator", "Mistrz pikseli"] },
  es: { level: "Nivel", challenge: "Desafío", currentFrame: "Ahora dibujas el fotograma", frame: "Fotograma", retry: "Mejorar resultado", started: "Desafío iniciado — el modelo siempre está cerca", similarity: "similitud con el modelo", colors: "cantidad de colores", frames: "cantidad de fotogramas", motion: "movimiento entre fotogramas", sequence: "orden y aspecto de los fotogramas", completed: "Desafío completado", notReady: "Aún no está listo", improve: "Mejora", saved: "Gran trabajo. Tu progreso se ha guardado.", xpEarned: "XP ya obtenido", newResult: "Nuevo resultado guardado. ¡Continúa la racha!", bestUpdated: "Mejor resultado actualizado; el XP ya fue obtenido.", closed: "Modo desafío cerrado, tu dibujo está guardado", ranks: ["Principiante", "Artista píxel", "Animador", "Maestro píxel"] },
  tr: { level: "Seviye", challenge: "Görev", currentFrame: "Şimdi çizilen kare", frame: "Kare", retry: "Sonucu geliştir", started: "Görev başladı — örnek her zaman yanında", similarity: "örneğe benzerlik", colors: "renk sayısı", frames: "kare sayısı", motion: "kareler arası hareket", sequence: "kare sırası ve görünümü", completed: "Görev tamamlandı", notReady: "Henüz hazır değil", improve: "Geliştir", saved: "Harika iş. İlerlemen kaydedildi.", xpEarned: "XP zaten alındı", newResult: "Yeni sonuç kaydedildi. Seriyi sürdür!", bestUpdated: "En iyi sonuç güncellendi; bu görevin XP'si zaten alınmıştı.", closed: "Görev modu kapatıldı, çizimin güvende", ranks: ["Acemi", "Piksel sanatçısı", "Animatör", "Piksel ustası"] },
  pt: { level: "Nível", challenge: "Desafio", currentFrame: "Agora desenhe o quadro", frame: "Quadro", retry: "Melhorar resultado", started: "Desafio iniciado — o modelo está sempre ao lado", similarity: "semelhança com o modelo", colors: "quantidade de cores", frames: "quantidade de quadros", motion: "movimento entre quadros", sequence: "ordem e aparência dos quadros", completed: "Desafio concluído", notReady: "Ainda não está pronto", improve: "Melhore", saved: "Ótimo trabalho. Seu progresso foi salvo.", xpEarned: "XP já recebido", newResult: "Novo resultado salvo. Continue a sequência!", bestUpdated: "Melhor resultado atualizado; o XP desta missão já foi recebido.", closed: "Modo desafio fechado, seu desenho está salvo", ranks: ["Iniciante", "Artista pixel", "Animador", "Mestre pixel"] },
  id: { level: "Level", challenge: "Tantangan", currentFrame: "Sekarang gambar frame", frame: "Frame", retry: "Tingkatkan hasil", started: "Tantangan dimulai — contoh selalu tersedia", similarity: "kemiripan dengan contoh", colors: "jumlah warna", frames: "jumlah frame", motion: "gerakan antar-frame", sequence: "urutan dan tampilan frame", completed: "Tantangan selesai", notReady: "Belum siap", improve: "Perbaiki", saved: "Kerja bagus. Progresmu telah disimpan.", xpEarned: "XP sudah diterima", newResult: "Hasil baru disimpan. Lanjutkan rentetan!", bestUpdated: "Skor terbaik diperbarui; XP misi ini sudah diterima.", closed: "Mode tantangan ditutup, gambarmu tersimpan", ranks: ["Pemula", "Seniman piksel", "Animator", "Master piksel"] }
};
export function challengeUi(language, key) {
  return CHALLENGE_UI[language]?.[key] || CHALLENGE_UI.en[key] || key;
}
